"""SIMULATED Pune mobility demand.

There is no open source of Pune taxi or ride-hail trips (docs/PUNE_DATA_SOURCES.md), so demand here
is generated by a documented model and is labelled SIMULATED everywhere it appears. What is real is
the context it is conditioned on: hourly rain from the ERA5 archive and the Maharashtra holiday
calendar, plus real geography (OpenStreetMap suburbs). What is assumed is the shape of demand: which
places generate trips, when, and how strongly. Those assumptions are the constants in this file;
change them and the results change. Nothing computed from this data says anything about real
Pune traffic.

Model, per zone z, day d, hour h:

    lambda = CITY_TRIPS_PER_DAY * weight[z] * shape[z, h] / 24 * day_factor[z, d] * rain[h] + events
    pickups ~ Poisson(lambda)

* ``weight``  a gravity model: employment, transit and leisure hubs plus a small residential term
* ``shape``   hour-of-day profile mixed from residential, business and leisure profiles by zone type
* ``day_factor``  weekday/weekend and holiday effects, plus day-level and zone-day noise
* ``rain``    +6% per mm of that hour's rain, capped at +30% (people take cars when it pours)
* ``events``  a few planted surges and drops (a rate multiplier on a zone's hours), recorded so a
  detector can be scored against them

Each day is a pure function of (seed, date, weather), so the batch build and the live worker
produce the same numbers for the same day.
"""

from __future__ import annotations

import math
from dataclasses import asdict, dataclass
from datetime import date, timedelta
from typing import Any

import numpy as np
import pandas as pd
from scipy.stats import poisson

from mobilityops.city import PUNE, City
from mobilityops.pune.zones import EARTH_RADIUS_M

SIMULATED_LABEL = "SIMULATED DEMAND"
HOURS = 24
CITY_TRIPS_PER_DAY = 40_000  # illustrative scale, chosen so busy zone-hours have countable demand
RAIN_PER_MM = 0.06
RAIN_CAP = 0.30
DAY_SIGMA = 0.06  # city-wide day-to-day variation
ZONE_DAY_SIGMA = 0.05  # zone-level day-to-day variation
CENTRE = (18.5204, 73.8567)  # Pune city centre (used for the sector label and residential term)
RESIDENTIAL_WEIGHT = 0.12
RESIDENTIAL_DECAY_KM = 6.0


@dataclass(frozen=True)
class Hub:
    """A trip-generating place. Coordinates are approximate landmarks: an assumption, not data."""

    name: str
    lat: float
    lon: float
    kind: str  # business | transit | leisure
    weight: float
    decay_km: float = 2.5


HUBS: tuple[Hub, ...] = (
    Hub("Hinjewadi IT Park", 18.5912, 73.7389, "business", 1.6, 3.0),
    Hub("Kharadi", 18.5515, 73.9400, "business", 1.2, 2.5),
    Hub("Magarpatta", 18.5146, 73.9287, "business", 1.0, 2.0),
    Hub("Baner-Balewadi", 18.5590, 73.7868, "business", 0.8, 2.5),
    Hub("Shivajinagar", 18.5308, 73.8475, "business", 1.0, 2.0),
    Hub("Pune Station", 18.5286, 73.8746, "transit", 1.3, 1.6),
    Hub("Swargate", 18.5018, 73.8636, "transit", 1.0, 1.6),
    Hub("Pune Airport", 18.5822, 73.9197, "transit", 0.6, 2.0),
    Hub("Koregaon Park", 18.5362, 73.8938, "leisure", 0.9, 1.8),
    Hub("Deccan-FC Road", 18.5169, 73.8412, "leisure", 0.9, 1.6),
)

# fmt: off
_RESIDENTIAL = np.array(
    [0.30, 0.20, 0.15, 0.15, 0.30, 0.70, 1.30, 1.90, 1.80, 1.30, 1.00, 0.95,
     1.00, 0.95, 0.95, 1.05, 1.20, 1.40, 1.40, 1.20, 1.00, 0.80, 0.55, 0.40]
)
_BUSINESS = np.array(
    [0.30, 0.20, 0.15, 0.15, 0.25, 0.50, 0.90, 1.50, 1.90, 1.60, 1.10, 1.10,
     1.20, 1.10, 1.00, 1.10, 1.30, 1.70, 1.90, 1.50, 1.00, 0.80, 0.55, 0.40]
)
_LEISURE = np.array(
    [0.60, 0.40, 0.25, 0.15, 0.10, 0.10, 0.20, 0.40, 0.60, 0.80, 0.90, 1.10,
     1.30, 1.20, 1.10, 1.20, 1.30, 1.50, 1.80, 2.10, 2.20, 2.00, 1.50, 1.00]
)
# fmt: on
_SHAPES = {
    name: arr / arr.mean()
    for name, arr in (("res", _RESIDENTIAL), ("biz", _BUSINESS), ("lei", _LEISURE))
}
# Monday=0 .. Sunday=6: business zones drop at weekends, leisure zones rise
_DOW = {
    "biz": np.array([1.05, 1.08, 1.08, 1.06, 1.02, 0.55, 0.40]),
    "lei": np.array([0.85, 0.85, 0.90, 0.95, 1.15, 1.40, 1.25]),
    "res": np.array([0.98, 1.00, 1.00, 1.00, 1.05, 1.05, 0.95]),
}
HOLIDAY_FACTOR = {"biz": 0.45, "lei": 1.25, "res": 0.95}


@dataclass(frozen=True)
class Event:
    zone: int
    date: str  # ISO date, city local
    start_hour: int
    hours: int
    factor: float
    kind: str  # surge | drop
    label: str


def _dist_km(lat1: float, lon1: float, lat2: np.ndarray, lon2: np.ndarray) -> np.ndarray:
    """Equirectangular distance in km; accurate to well under 1% across the study area."""
    x = np.radians(lon2 - lon1) * math.cos(math.radians(lat1))
    y = np.radians(lat2 - lat1)
    return np.asarray(np.hypot(x, y) * EARTH_RADIUS_M / 1000.0)


def sector(lat: float, lon: float) -> str:
    """Compass sector of the city centre, or ``Central`` within 3 km. Used as the zone group."""
    d = float(_dist_km(CENTRE[0], CENTRE[1], np.array([lat]), np.array([lon]))[0])
    if d < 3.0:
        return "Central"
    brg = (math.degrees(math.atan2(lon - CENTRE[1], lat - CENTRE[0])) + 360) % 360
    names = (
        "North",
        "North-East",
        "East",
        "South-East",
        "South",
        "South-West",
        "West",
        "North-West",
    )
    return names[int(((brg + 22.5) % 360) // 45)]


@dataclass(frozen=True)
class ZoneModel:
    zone_ids: np.ndarray  # (Z,)
    weight: np.ndarray  # (Z,) share of city trips, sums to 1
    mix: np.ndarray  # (Z, 3) business / leisure / residential mix, rows sum to 1
    shape: np.ndarray  # (Z, 24) hour profile, mean 1 per row
    dow: np.ndarray  # (Z, 7)
    holiday: np.ndarray  # (Z,)
    dropoff: np.ndarray  # (Z, Z) row-stochastic origin -> destination
    fare_inr: np.ndarray  # (Z,) mean fare of a trip starting in the zone


def build_model(zones: pd.DataFrame) -> ZoneModel:
    """Derive the demand model from ``zones`` (location_id, centroid_lat, centroid_lon)."""
    ids = zones["location_id"].to_numpy(dtype=int)
    lat = zones["centroid_lat"].to_numpy(dtype=float)
    lon = zones["centroid_lon"].to_numpy(dtype=float)
    n = len(ids)
    mass = {"business": np.zeros(n), "transit": np.zeros(n), "leisure": np.zeros(n)}
    for hub in HUBS:
        d = _dist_km(hub.lat, hub.lon, lat, lon)
        mass[hub.kind] += hub.weight * np.exp(-d / hub.decay_km)
    d_centre = _dist_km(CENTRE[0], CENTRE[1], lat, lon)
    resid = RESIDENTIAL_WEIGHT * np.exp(-d_centre / RESIDENTIAL_DECAY_KM)
    biz = mass["business"] + 0.5 * mass["transit"]
    lei = mass["leisure"] + 0.5 * mass["transit"]
    total = biz + lei + resid
    weight = total / total.sum()
    mix = np.stack([biz, lei, resid], axis=1) / total[:, None]
    shape = (
        mix[:, 0:1] * _SHAPES["biz"] + mix[:, 1:2] * _SHAPES["lei"] + mix[:, 2:3] * _SHAPES["res"]
    )
    shape = shape / shape.mean(axis=1, keepdims=True)
    dow = mix[:, 0:1] * _DOW["biz"] + mix[:, 1:2] * _DOW["lei"] + mix[:, 2:3] * _DOW["res"]
    holiday = (
        mix[:, 0] * HOLIDAY_FACTOR["biz"]
        + mix[:, 1] * HOLIDAY_FACTOR["lei"]
        + mix[:, 2] * HOLIDAY_FACTOR["res"]
    )
    # gravity destinations: trips go to places with the same mass that lie within ~5 km
    pair = np.hypot(
        (lon[:, None] - lon[None, :]) * math.cos(math.radians(CENTRE[0])),
        lat[:, None] - lat[None, :],
    ) * (math.pi / 180.0 * EARTH_RADIUS_M / 1000.0)
    attract = weight[None, :] * np.exp(-pair / 5.0)
    drop = attract / attract.sum(axis=1, keepdims=True)
    trip_km = (drop * pair).sum(axis=1)
    return ZoneModel(ids, weight, mix, shape, dow, holiday, drop, 90.0 + 11.0 * trip_km)


EVENT_DAY_PROBABILITY = 0.05  # about eighteen planted events a year


def events_for_day(model: ZoneModel, day: date, seed: int) -> list[Event]:
    """The planted events of one day: a pure function of (seed, date), so the batch build and the
    live worker agree. Surges sit in evening hours at busy zones; drops in the morning."""
    rng = np.random.default_rng([seed, day.toordinal(), 991])
    if rng.random() >= EVENT_DAY_PROBABILITY:
        return []
    top = np.argsort(-model.weight)[:12]
    zone = int(model.zone_ids[int(rng.choice(top))])
    drop = bool(rng.random() < 0.25)
    return [
        Event(
            zone=zone,
            date=day.isoformat(),
            start_hour=int(rng.integers(8, 12)) if drop else int(rng.integers(17, 21)),
            hours=int(rng.integers(3, 6)),
            factor=round(
                float(rng.uniform(0.25, 0.4)) if drop else float(rng.uniform(1.8, 2.6)), 2
            ),
            kind="drop" if drop else "surge",
            label="simulated service disruption" if drop else "simulated crowd event",
        )
    ]


def plan_events(model: ZoneModel, days: list[date], seed: int) -> list[Event]:
    """Planted events for a run of days, recorded so a detector can be scored against them."""
    return [e for d in days for e in events_for_day(model, d, seed)]


def rain_multiplier(precip_mm: np.ndarray) -> np.ndarray:
    """Per-hour demand multiplier from rain; unknown (NaN) rain has no effect."""
    p = np.nan_to_num(np.asarray(precip_mm, dtype=float), nan=0.0)
    return np.asarray(1.0 + np.minimum(RAIN_PER_MM * p, RAIN_CAP))


def simulate_day(
    model: ZoneModel,
    day: date,
    precip_mm: np.ndarray,
    is_holiday: bool,
    seed: int,
    events: list[Event] | None = None,
) -> np.ndarray:
    """Pickups for one local day as an int array ``(zones, 24)``; a pure function of its inputs."""
    rng = np.random.default_rng([seed, day.toordinal()])
    day_noise = math.exp(rng.normal(0.0, DAY_SIGMA))
    zone_noise = np.exp(rng.normal(0.0, ZONE_DAY_SIGMA, size=len(model.zone_ids)))
    dow = model.dow[:, day.weekday()]
    hol = model.holiday if is_holiday else np.ones(len(model.zone_ids))
    lam = (
        CITY_TRIPS_PER_DAY
        * model.weight[:, None]
        * model.shape
        / HOURS
        * (dow * hol * zone_noise * day_noise)[:, None]
        * rain_multiplier(precip_mm)[None, :]
    )
    for ev in events or ():
        if ev.date != day.isoformat():
            continue
        zi = int(np.where(model.zone_ids == ev.zone)[0][0])
        lam[zi, ev.start_hour : min(HOURS, ev.start_hour + ev.hours)] *= ev.factor
    # One fixed uniform per cell, turned into a count by the Poisson quantile function. This is
    # exactly Poisson(lambda), and it makes every cell independent of every other cell's rate:
    # new rain data for one hour, or a planted event, changes only the cells whose rate changed
    # (and monotonically), never the noise of anything else. A sampler that draws counts directly
    # consumes a lambda-dependent amount of randomness and would reshuffle the rest of the day.
    u = rng.random(lam.shape) * (1.0 - 2e-12) + 1e-12
    return np.asarray(poisson.ppf(u, lam), dtype=np.int64)


def allocate_dropoffs(pickups: np.ndarray, model: ZoneModel) -> np.ndarray:
    """Dropoffs ``(zones, hours)`` from pickups ``(zones, hours)``: each hour's trips go to
    destinations by the gravity matrix, rounded so the total per hour is preserved exactly."""
    expected = model.dropoff.T @ pickups  # (Z, H)
    base = np.floor(expected).astype(np.int64)
    short = pickups.sum(axis=0) - base.sum(axis=0)  # trips still to place, per hour
    frac = expected - base
    order = np.argsort(-frac, axis=0)
    ranks = np.empty_like(order)
    np.put_along_axis(ranks, order, np.arange(expected.shape[0])[:, None], axis=0)
    return base + (ranks < short[None, :]).astype(np.int64)


def simulate_range(
    model: ZoneModel,
    days: list[date],
    hourly_rain: pd.DataFrame,
    city: City = PUNE,
    seed: int = 20260924,
    events: list[Event] | None = None,
) -> pd.DataFrame:
    """Long frame ``location_id, hour_ts, pickups, dropoffs, revenue, passengers`` for ``days``.

    ``hourly_rain`` has ``hour_ts`` (naive local) and ``precipitation`` (mm). Missing hours are
    treated as no rain. Holidays come from ``city``.
    """
    rain = hourly_rain.set_index("hour_ts")["precipitation"]
    holidays = city.holidays(days[0], days[-1])
    frames = []
    for d in days:
        idx = pd.date_range(pd.Timestamp(d), periods=HOURS, freq="h")
        p = rain.reindex(idx).to_numpy()
        pick = simulate_day(model, d, p, d in holidays, seed, events)
        drop = allocate_dropoffs(pick, model)
        rev = pick * model.fare_inr[:, None]
        pax = np.round(pick * 1.3).astype(np.int64)
        z = np.repeat(model.zone_ids, HOURS)
        frames.append(
            pd.DataFrame(
                {
                    "location_id": z,
                    "hour_ts": np.tile(idx.to_numpy(), len(model.zone_ids)),
                    "pickups": pick.ravel().astype(np.int32),
                    "dropoffs": drop.ravel().astype(np.int32),
                    "revenue": rev.ravel().astype(float),
                    "passengers": pax.ravel().astype(float),
                }
            )
        )
    return pd.concat(frames, ignore_index=True)


def model_card() -> dict[str, Any]:
    """The assumptions, for the API and documentation."""
    return {
        "label": SIMULATED_LABEL,
        "city_trips_per_day": CITY_TRIPS_PER_DAY,
        "rain_effect": f"+{RAIN_PER_MM:.0%} per mm, capped at +{RAIN_CAP:.0%}",
        "day_noise_sigma": DAY_SIGMA,
        "zone_day_noise_sigma": ZONE_DAY_SIGMA,
        "hubs": [asdict(h) for h in HUBS],
        "holiday_factor": HOLIDAY_FACTOR,
        "caveat": "Demand is generated by this model. It is conditioned on real rain and the real "
        "holiday calendar, but its level and shape are assumptions.",
    }


def date_range(start: date, end: date) -> list[date]:
    """Days in [start, end)."""
    return [start + timedelta(days=i) for i in range((end - start).days)]
