import { ChartPanel, DataClassTag } from "../../ui";

const ROWS: { what: string; kind: string; real: string; note: string }[] = [
  { what: "Mobility demand (pickups, dropoffs)", kind: "SIMULATED", real: "No", note: "No open Pune trip source exists. A documented model generates the counts." },
  { what: "Rain, hourly", kind: "RECENT", real: "Yes (model output)", note: "Open-Meteo: ERA5 history plus the recent-hours model output. Drives the simulated demand." },
  { what: "Weather now", kind: "NEAR-REAL-TIME", real: "Yes (model output)", note: "Latest 15-minute model step at 9 points, not a station reading." },
  { what: "Air quality now", kind: "NEAR-REAL-TIME", real: "Yes (model output)", note: "CAMS atmospheric-composition model, coarse grid. Not a monitoring station." },
  { what: "Holidays", kind: "STATIC", real: "Yes", note: "The Maharashtra and India public-holiday calendar; many dates follow lunar calendars." },
  { what: "Zones and map", kind: "STATIC", real: "Yes", note: "OpenStreetMap suburbs; each zone is the area closest to one suburb. Not administrative wards." },
  { what: "Forecasts", kind: "PREDICTED", real: "Computed", note: "LightGBM day-ahead model with an 80% conformal range, trained on the simulated history." },
  { what: "Events", kind: "SIMULATED", real: "Computed", note: "A documented rule on simulated demand against the forecast." },
];

export function MethodPage() {
  return (
    <div className="stack">
      <ChartPanel title="What is real here, and what is not" subtitle="Read this before reading any number">
        <p>
          MobilityOps Pune is a working real-time data platform built on a simulated demand signal. The plumbing is real:
          sources are polled on schedules, validated, stored, forecast against, and shown with their freshness. The trip counts
          are not: nobody publishes Pune taxi or ride-hail trips openly, so demand is generated by a model and labelled
          SIMULATED wherever it appears. Nothing on these screens describes real Pune traffic.
        </p>
        <div className="table-wrap">
          <table className="ops-table">
            <caption className="sr-only">Every kind of data on the dashboard</caption>
            <thead><tr><th scope="col">Data</th><th scope="col">Class</th><th scope="col">Real input?</th><th scope="col">Notes</th></tr></thead>
            <tbody>
              {ROWS.map((r) => (
                <tr key={r.what}>
                  <th scope="row">{r.what}</th>
                  <td><DataClassTag kind={r.kind} /></td>
                  <td className="small">{r.real}</td>
                  <td className="small">{r.note}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </ChartPanel>
      <div className="two-col">
        <ChartPanel title="What the labels mean">
          <ul className="plain small">
            <li><DataClassTag kind="LIVE" /> observations within seconds. Not used for Pune: no such source exists.</li>
            <li><DataClassTag kind="NEAR-REAL-TIME" /> the latest model or observation step, minutes old by design.</li>
            <li><DataClassTag kind="RECENT" /> within the last day or so.</li>
            <li><DataClassTag kind="HISTORICAL" /> complete past data.</li>
            <li><DataClassTag kind="PREDICTED" /> a forecast, always with a range.</li>
            <li><DataClassTag kind="SIMULATED" /> produced by a model, not observed.</li>
          </ul>
          <p className="small muted">
            Freshness (LIVE, DELAYED, STALE, OFFLINE) is a separate idea: it says how old a value is, computed from the
            source&apos;s own timestamps. A SIMULATED value can be LIVE-fresh; that only means the simulator ran on schedule.
          </p>
        </ChartPanel>
        <ChartPanel title="Attribution and licences">
          <ul className="plain small">
            <li>Weather and air quality: Open-Meteo.com, CC BY 4.0, free tier for non-commercial use.</li>
            <li>Map data: © OpenStreetMap contributors, ODbL 1.0.</li>
            <li>Air-quality model data: Copernicus Atmosphere Monitoring Service via Open-Meteo.</li>
            <li>Code: MIT.</li>
          </ul>
          <p className="small muted">
            Traffic (TomTom), station air quality (OpenAQ) and the PMPML bus timetable have adapters or notes but are not
            connected: they need a key or a feed the operator supplies.
          </p>
        </ChartPanel>
      </div>
    </div>
  );
}
