"""Write requirements.lock: the exact Python package versions currently installed.

Used as pip *constraints* by the Docker build so an image reproduces the environment the reported
results were produced with. Run `make lock` after upgrading dependencies (and after re-running the
evaluations, since library versions can change numeric results).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

HEADER = f"""# Exact package versions the reported results were produced with
# (Python {sys.version.split()[0]}, {sys.platform}).
# Generated by `make lock`; used as pip constraints (pip install -c requirements.lock ...) by the
# Docker build. It constrains versions; it does not add dependencies.
"""


def main() -> int:
    out = subprocess.run(
        [sys.executable, "-m", "pip", "freeze", "--exclude-editable"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    pins = sorted(
        (ln for ln in out.splitlines() if ln and not ln.lower().startswith("mobilityops")),
        key=str.lower,
    )
    Path(__file__).resolve().parents[1].joinpath("requirements.lock").write_text(
        HEADER + "\n".join(pins) + "\n"
    )
    print(f"wrote requirements.lock ({len(pins)} pins)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
