package com.jayraj.mobilityops.pune

import android.content.Context
import android.os.Handler
import android.os.Looper
import android.view.View
import android.widget.LinearLayout
import androidx.core.content.ContextCompat
import com.jayraj.mobilityops.R
import com.jayraj.mobilityops.ui.ScreenFragment
import com.jayraj.mobilityops.ui.Ui

/**
 * Base for the Pune screens. It shares one stream with every other Pune screen, redraws when new
 * data arrives, and every few seconds so "12 s ago" keeps counting between updates.
 */
abstract class PuneScreen : ScreenFragment() {
    protected var st: PuneState = PuneHub.state
    private var unobserve: (() -> Unit)? = null
    private val clock = Handler(Looper.getMainLooper())
    private val tick = object : Runnable {
        override fun run() {
            if (content != null) {
                redraw()
                clock.postDelayed(this, 5_000)
            }
        }
    }

    /** Draw the screen from ``st``; called on every redraw. Keep loaded data in fields, never refetch here. */
    protected abstract fun render(c: Context)

    /** Called when a new snapshot arrives (its ``seq`` changed): reload anything derived from the store. */
    protected open fun onNewData() {}

    override fun build(c: Context) = render(c)

    protected fun redraw() {
        val box = content ?: return
        box.removeAllViews()
        render(requireContext())
    }

    override fun onStart() {
        super.onStart()
        PuneHub.acquire(api())
        var lastSeq = -1L
        unobserve = PuneHub.observe { s ->
            st = s
            val seq = s.snapshot?.seq ?: -1
            if (seq != lastSeq) {
                lastSeq = seq
                onNewData()
            }
            if (content != null) redraw()
        }
        clock.postDelayed(tick, 5_000)
    }

    override fun onStop() {
        clock.removeCallbacks(tick)
        unobserve?.invoke()
        unobserve = null
        PuneHub.release()
        super.onStop()
    }

    protected val now: Long get() = System.currentTimeMillis()
    protected val elapsed: Double get() = st.elapsedSeconds(now)

    /** The two things that must be on every screen: what the data is, and whether it is current. */
    protected fun header(c: Context, title: String) {
        val box: LinearLayout = content ?: return
        box.addView(Ui.heading(c, title))
        box.addView(
            Ui.banner(
                c, "SIMULATED DEMAND",
                "on real weather and geography. Pune publishes no open trip data, so trip counts are generated by a model. " +
                    "Nothing here describes real Pune traffic.",
                R.color.replay_bg, R.color.replay_border,
            ),
        )
        st.notice()?.let { box.addView(Ui.banner(c, "Not current", it, R.color.surface, R.color.warn)) }
        if (st.unavailable && st.snapshot == null) {
            box.addView(
                Ui.banner(
                    c, "The ingestion worker is not running",
                    "Start it with: python -m mobilityops.cli pune-worker. Nothing is shown until it has written data.",
                    R.color.surface, R.color.border,
                ),
            )
        }
    }

    protected fun freshnessLine(c: Context, f: Freshness, age: Double?, prefix: String = ""): View {
        val t = Ui.text(c, "$prefix${f.badge()}${if (age != null && f in ACTIVE) " · ${ageText(age)}" else ""}", 13f, f.color, true)
        t.contentDescription = "$prefix${f.label}. ${f.help}"
        return t
    }

    companion object {
        val ACTIVE = setOf(Freshness.LIVE, Freshness.DELAYED, Freshness.STALE, Freshness.OFFLINE)
        fun fmtInt(x: Double?): String = if (x == null) "n/a" else String.format(java.util.Locale.US, "%,d", Math.round(x))
        fun pct(ratio: Double?): String? =
            ratio?.let { (if (it >= 1) "+" else "−") + Math.abs(Math.round((it - 1) * 100)) + "% vs forecast" }
    }

    protected fun color(res: Int): Int = ContextCompat.getColor(requireContext(), res)
}
