/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyst/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyst Ask
         * @description Ask a question. Refusals, clarifications and partial answers are normal results.
         */
        post: operations["analyst_ask_api_v1_analyst_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyst/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analyst Status */
        get: operations["analyst_status_api_v1_analyst_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyst/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analyst Tools */
        get: operations["analyst_tools_api_v1_analyst_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Anomalies
         * @description Detected events, largest first. Explanations describe coincidence, never cause.
         */
        get: operations["anomalies_api_v1_anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/anomalies/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anomalies Summary */
        get: operations["anomalies_summary_api_v1_anomalies_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_api_v1_demand_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/concentration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Concentration */
        get: operations["concentration_api_v1_demand_concentration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/growth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Growth */
        get: operations["growth_api_v1_demand_growth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/profile/hourly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hourly Profile */
        get: operations["hourly_profile_api_v1_demand_profile_hourly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/profile/weekday": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekday Profile */
        get: operations["weekday_profile_api_v1_demand_profile_weekday_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demand Series */
        get: operations["demand_series_api_v1_demand_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service Mix
         * @description Pickups per service (yellow, green, for-hire) and each one's share, by month or total.
         */
        get: operations["service_mix_api_v1_demand_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/services/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service Profile
         * @description Average pickups by hour of day for each service.
         */
        get: operations["service_profile_api_v1_demand_services_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/top-zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top Zones */
        get: operations["top_zones_api_v1_demand_top_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/volatility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Volatility */
        get: operations["volatility_api_v1_demand_volatility_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demand/weather-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weather Comparison */
        get: operations["weather_comparison_api_v1_demand_weather_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forecast Backtest
         * @description Out-of-sample forecast vs actual for one zone and day, from the evaluation folds.
         */
        get: operations["forecast_backtest_api_v1_forecast_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forecast Model
         * @description The registered model's metadata (training windows, features, parameters).
         */
        get: operations["forecast_model_api_v1_forecast_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/next-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forecast Next Day
         * @description Forecast for the day after the last observed day, per zone or city-wide total.
         */
        get: operations["forecast_next_day_api_v1_forecast_next_day_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forecast Performance
         * @description The latest walk-forward evaluation (metrics, baselines, error analysis, intervals).
         */
        get: operations["forecast_performance_api_v1_forecast_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Snapshot
         * @description The current state in one document: the replay's recent hours and the latest feed data.
         */
        get: operations["live_snapshot_api_v1_live_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Status
         * @description Whether the replay is available, how many streams are open, and the replay's clock.
         */
        get: operations["live_status_api_v1_live_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Stream
         * @description Server-sent events: ``hello``, then ``replay`` (hourly ticks of held-out days, labelled
         *     REPLAY), ``feed`` (live Citi Bike and weather) and ``history`` events. ``limit`` stops the
         *     stream after that many events (useful for tests and ``curl``).
         */
        get: operations["live_stream_api_v1_live_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ops Metrics
         * @description Request counts and latency percentiles per route template, plus analyst counters.
         */
        get: operations["ops_metrics_api_v1_ops_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Optimization Backtest
         * @description The latest repositioning backtest. SIMULATED under explicit assumptions.
         */
        get: operations["optimization_backtest_api_v1_optimization_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimization Scenario
         * @description Run one repositioning what-if. SIMULATED SCENARIO under the stated assumptions.
         *
         *     Bounded: at most a few solves run at once (others get 429) and each stops after
         *     ``SOLVER_TIME_LIMIT_S`` seconds.
         */
        post: operations["optimization_scenario_api_v1_optimization_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality */
        get: operations["quality_api_v1_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zones */
        get: operations["zones_api_v1_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/zones/{zone_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zone */
        get: operations["zone_api_v1_zones__zone_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: which parts are available */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalystFact */
        AnalystFact: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** AnalystRequest */
        AnalystRequest: {
            /** Question */
            question: string;
        };
        /** AnalystResponse */
        AnalystResponse: {
            /** Data Label */
            data_label: string;
            /** Grounding */
            grounding: {
                [key: string]: number;
            };
            /** Intent */
            intent: string;
            /** Mode */
            mode: string;
            /** Question */
            question: string;
            /** Statements */
            statements: components["schemas"]["AnalystStatement"][];
            /**
             * Status
             * @enum {string}
             */
            status: "answered" | "partial" | "clarify" | "refused" | "no_data";
            /** Tools Used */
            tools_used: components["schemas"]["AnalystToolTrace"][];
            /** Warnings */
            warnings: string[];
        };
        /** AnalystStatement */
        AnalystStatement: {
            /** Fact Ids */
            fact_ids: string[];
            /**
             * Kind
             * @enum {string}
             */
            kind: "FACT" | "INTERPRETATION" | "ASSUMPTION" | "LIMITATION";
            /** Text */
            text: string;
        };
        /** AnalystStatus */
        AnalystStatus: {
            /** Llm Configured */
            llm_configured: boolean;
            /** Llm Status */
            llm_status: string;
            /** Note */
            note: string;
            /** Planner */
            planner: string;
            /** Tools */
            tools: number;
        };
        /** AnalystToolTrace */
        AnalystToolTrace: {
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /** Call Id */
            call_id: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
            /** Facts */
            facts: components["schemas"]["AnalystFact"][];
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
        };
        /** AnomalyItem */
        AnomalyItem: {
            /** Actual */
            actual: number;
            /** Borough */
            borough: string;
            /** Citywide Share */
            citywide_share: number;
            /** Context */
            context: string[];
            /**
             * Direction
             * @enum {string}
             */
            direction: "surge" | "drop";
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Event Id */
            event_id: number;
            /** Event Z */
            event_z: number;
            /** Excess */
            excess: number;
            /** Explanation */
            explanation: string;
            /** Forecast */
            forecast: number;
            /** Hours Flagged */
            hours_flagged: number;
            /** Hours Span */
            hours_span: number;
            /** Location Id */
            location_id: number;
            /** Overlapping Events */
            overlapping_events: number;
            /** Peak Z */
            peak_z: number;
            /** Ratio */
            ratio: number | null;
            /** Scope */
            scope: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "medium" | "high";
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Zone */
            zone: string;
        };
        /** AnomalyPage */
        AnomalyPage: {
            /** Accuracy Status */
            accuracy_status: string;
            /** Data Label */
            data_label: string;
            /** Items */
            items: components["schemas"]["AnomalyItem"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * ArtifactDocument
         * @description A generated report served as-is (its own ``data_label`` and status wording are kept).
         */
        ArtifactDocument: {
            [key: string]: unknown;
        };
        /** BacktestForecast */
        BacktestForecast: {
            /** Data Label */
            data_label: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Note */
            note: string;
            /** Points */
            points: components["schemas"]["ForecastPoint"][];
            /** Zone Id */
            zone_id: number;
            /** Zone Name */
            zone_name: string;
        };
        /** Comparison */
        Comparison: {
            /** Equal Length */
            equal_length: boolean;
            /** Metric */
            metric: string;
            /** Per Day Change */
            per_day_change: number;
            /** Per Day Change Pct */
            per_day_change_pct: number | null;
            period_a: components["schemas"]["PeriodTotals"];
            period_b: components["schemas"]["PeriodTotals"];
            /** Zone Id */
            zone_id: number | null;
        };
        /** Concentration */
        Concentration: {
            /**
             * Herfindahl Index
             * @description Computed over every zone with demand in the period.
             */
            herfindahl_index: number;
            /** Share Covered By Top 100 */
            share_covered_by_top_100?: number | null;
            /** Top N */
            top_n: number;
            /** Top N Share */
            top_n_share: number;
            /**
             * Zones Counted
             * @description Number of zones with demand that the index covers.
             */
            zones_counted?: number | null;
        };
        /** ForecastPoint */
        ForecastPoint: {
            /** Actual */
            actual?: number | null;
            /** Forecast */
            forecast: number;
            /** Hi */
            hi?: number | null;
            /**
             * Hour Ts
             * Format: date-time
             */
            hour_ts: string;
            /** Lo */
            lo?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status?: "ok";
        };
        /** HourProfilePoint */
        HourProfilePoint: {
            /** Avg Pickups */
            avg_pickups: number;
            /** Hour Of Day */
            hour_of_day: number;
            /** N Hours */
            n_hours: number;
        };
        /** Meta */
        Meta: {
            /** Api Version */
            api_version: string;
            /** Artifacts */
            artifacts: {
                [key: string]: boolean;
            };
            /** Built At Utc */
            built_at_utc: string;
            /**
             * City
             * @default New York City
             */
            city?: string;
            /**
             * Data End
             * Format: date-time
             * @description Exclusive end of the data window (local time).
             */
            data_end: string;
            /** Data Label */
            data_label: string;
            /**
             * Data Start
             * Format: date-time
             */
            data_start: string;
            /** Llm Configured */
            llm_configured: boolean;
            /**
             * Mode
             * @enum {string}
             */
            mode: "sample" | "real" | "pune";
            /** N Zones */
            n_zones: number;
            /** Rows Valid */
            rows_valid: number;
            /** Run Id */
            run_id: string;
            /**
             * Services
             * @description Services in the data. Only 'yellow' unless green / for-hire files were built.
             * @default []
             */
            services?: components["schemas"]["ServiceInfo"][];
            /** Synthetic */
            synthetic: boolean;
            /**
             * Timezone
             * @default America/New_York (timestamps are naive local time)
             */
            timezone?: string;
        };
        /** Move */
        Move: {
            /** From Name */
            from_name: string;
            /** From Zone */
            from_zone: number;
            /** Km */
            km: number;
            /** To Name */
            to_name: string;
            /** To Zone */
            to_zone: number;
            /** Vehicles */
            vehicles: number;
        };
        /** NextDayForecast */
        NextDayForecast: {
            /** Data Label */
            data_label: string;
            /** Empirical Coverage In Evaluation */
            empirical_coverage_in_evaluation: number | null;
            /** Model Id */
            model_id: string;
            /** Nominal Coverage */
            nominal_coverage: number;
            /** Note */
            note: string;
            /** Points */
            points: components["schemas"]["ForecastPoint"][];
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Zone Id */
            zone_id: number | null;
            /** Zone Name */
            zone_name: string | null;
        };
        /** PeriodTotals */
        PeriodTotals: {
            /** Days */
            days: number;
            /** Per Day */
            per_day: number;
            /** Total */
            total: number;
        };
        /** QualityCheck */
        QualityCheck: {
            /** Message */
            message: string;
            /**
             * Metrics
             * @default {}
             */
            metrics?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PASS" | "WARN" | "FAIL";
        };
        /** QualityStage */
        QualityStage: {
            /**
             * Overall
             * @enum {string}
             */
            overall: "PASS" | "WARN" | "FAIL";
            /** Results */
            results: components["schemas"]["QualityCheck"][];
            /** Stage */
            stage: string;
        };
        /** Ready */
        Ready: {
            /** Components */
            components: {
                [key: string]: boolean;
            };
            /** Hint */
            hint?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
        };
        /** ScenarioRequest */
        ScenarioRequest: {
            /**
             * Cost Per Km
             * @default 0.02
             */
            cost_per_km?: number;
            /**
             * Coverage
             * @description Fleet capacity / expected demand.
             * @default 0.85
             */
            coverage?: number;
            /**
             * Date
             * Format: date
             * @description An out-of-sample day (the evaluation days).
             */
            date: string;
            /**
             * Demand Multipliers
             * @description Zone id -> demand factor (a what-if shock).
             */
            demand_multipliers?: {
                [key: string]: number;
            };
            /**
             * End Hour
             * @default 20
             */
            end_hour?: number;
            /**
             * Max Km
             * @default 6
             */
            max_km?: number;
            /**
             * Max Move Share
             * @default 0.3
             */
            max_move_share?: number;
            /** Min Service Share */
            min_service_share?: number | null;
            /**
             * Start Hour
             * @default 17
             */
            start_hour?: number;
            /**
             * Trips Per Vehicle
             * @default 4.5
             */
            trips_per_vehicle?: number;
        };
        /** ScenarioResponse */
        ScenarioResponse: {
            /** Assumptions */
            assumptions: {
                [key: string]: unknown;
            };
            /** Best Attainable Service Share */
            best_attainable_service_share: number | null;
            /** Context */
            context: {
                [key: string]: unknown;
            };
            /** Data Label */
            data_label: string;
            /** Demand Total */
            demand_total: number;
            /** Fleet */
            fleet: number;
            /** Km Total */
            km_total: number;
            /** Label */
            label: string;
            /** Message */
            message: string;
            /** Moves */
            moves: components["schemas"]["Move"][];
            /** Served After */
            served_after: number;
            /** Served Before */
            served_before: number;
            /** Service Share After */
            service_share_after: number | null;
            /** Service Share Before */
            service_share_before: number | null;
            /** Solver */
            solver: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "optimal" | "feasible_time_limit" | "infeasible" | "no_solution" | "unbounded" | "solver_error";
            /** Vehicles Moved */
            vehicles_moved: number;
        };
        /** SeriesPoint */
        SeriesPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Value */
            value: number;
        };
        /** SeriesResponse */
        SeriesResponse: {
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Grain
             * @enum {string}
             */
            grain: "hour" | "day";
            /**
             * Metric
             * @enum {string}
             */
            metric: "pickups" | "dropoffs" | "revenue";
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Zone Id */
            zone_id: number | null;
            /** Zone Name */
            zone_name: string | null;
        };
        /** ServiceInfo */
        ServiceInfo: {
            /** Label */
            label: string;
            /** Service */
            service: string;
        };
        /** ServiceMixPoint */
        ServiceMixPoint: {
            /** Label */
            label: string;
            /**
             * Period
             * Format: date-time
             * @description Start of the month, or of the requested period.
             */
            period: string;
            /** Pickups */
            pickups: number;
            /** Service */
            service: string;
            /**
             * Share
             * @description Share of all listed services' cleaned pickups in the same period. Not a share of all mobility: subways, buses, private cars and older for-hire files are absent.
             */
            share: number;
        };
        /** ServiceProfilePoint */
        ServiceProfilePoint: {
            /** Avg Pickups */
            avg_pickups: number;
            /** Hour Of Day */
            hour_of_day: number;
            /** N Hours */
            n_hours: number;
            /** Service */
            service: string;
        };
        /** TopZone */
        TopZone: {
            /** Borough */
            borough: string;
            /** Location Id */
            location_id: number;
            /**
             * Share
             * @description Share of the citywide total for the same period.
             */
            share: number;
            /** Value */
            value: number;
            /** Zone */
            zone: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Volatility */
        Volatility: {
            /** Coefficient Of Variation */
            coefficient_of_variation: number | null;
            /** Days */
            days: number;
            /** Mean Daily */
            mean_daily: number;
            /** Std Daily */
            std_daily: number;
            /** Zone Id */
            zone_id: number;
        };
        /** WeatherComparison */
        WeatherComparison: {
            /** Caveat */
            caveat: string;
            /** Condition */
            condition: string;
            /** Days With */
            days_with: number;
            /** Days Without */
            days_without: number;
            /** Mean Daily With */
            mean_daily_with: number | null;
            /** Mean Daily Without */
            mean_daily_without: number | null;
            /** Raw Ratio */
            raw_ratio: number | null;
            /** Weekday Adjusted Ratio */
            weekday_adjusted_ratio: number | null;
            /** Zone Id */
            zone_id: number | null;
        };
        /** WeekdayPoint */
        WeekdayPoint: {
            /** Avg Daily Pickups */
            avg_daily_pickups: number;
            /**
             * Day Of Week
             * @description Monday = 0
             */
            day_of_week: number;
            /** N Days */
            n_days: number;
        };
        /** Zone */
        Zone: {
            /** Borough */
            borough: string;
            /** Centroid Lat */
            centroid_lat?: number | null;
            /** Centroid Lon */
            centroid_lon?: number | null;
            /** Location Id */
            location_id: number;
            /** Service Zone */
            service_zone?: string | null;
            /** Zone */
            zone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyst_ask_api_v1_analyst_ask_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalystRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalystResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyst_status_api_v1_analyst_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalystStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyst_tools_api_v1_analyst_tools_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anomalies_api_v1_anomalies_get: {
        parameters: {
            query?: {
                severity?: ("low" | "medium" | "high") | null;
                direction?: ("surge" | "drop") | null;
                /** @description TLC location id */
                zone_id?: number | null;
                start?: string | null;
                end?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anomalies_summary_api_v1_anomalies_summary_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_demand_compare_get: {
        parameters: {
            query: {
                a_start: string;
                a_end: string;
                b_start: string;
                b_end: string;
                /** @description TLC location id */
                zone_id?: number | null;
                metric?: "pickups" | "dropoffs" | "revenue";
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    concentration_api_v1_demand_concentration_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                top_n?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Concentration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    growth_api_v1_demand_growth_get: {
        parameters: {
            query: {
                end: string;
                window_days?: number;
                /** @description TLC location id */
                zone_id?: number | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hourly_profile_api_v1_demand_profile_hourly_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                /** @description TLC location id */
                zone_id?: number | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HourProfilePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weekday_profile_api_v1_demand_profile_weekday_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                /** @description TLC location id */
                zone_id?: number | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekdayPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demand_series_api_v1_demand_series_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                /** @description TLC location id */
                zone_id?: number | null;
                grain?: "hour" | "day";
                metric?: "pickups" | "dropoffs" | "revenue";
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    service_mix_api_v1_demand_services_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                /** @description TLC location id */
                zone_id?: number | null;
                grain?: "month" | "total";
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceMixPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    service_profile_api_v1_demand_services_profile_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                /** @description TLC location id */
                zone_id?: number | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceProfilePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    top_zones_api_v1_demand_top_zones_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                metric?: "pickups" | "dropoffs" | "revenue";
                limit?: number;
                ascending?: boolean;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopZone"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volatility_api_v1_demand_volatility_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                /** @description TLC location id */
                zone_id: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Volatility"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weather_comparison_api_v1_demand_weather_comparison_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                condition?: "rain" | "snow" | "freezing";
                /** @description TLC location id */
                zone_id?: number | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_backtest_api_v1_forecast_backtest_get: {
        parameters: {
            query: {
                /** @description TLC location id */
                zone_id: number;
                date: string;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestForecast"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_model_api_v1_forecast_model_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_next_day_api_v1_forecast_next_day_get: {
        parameters: {
            query?: {
                /** @description TLC location id */
                zone_id?: number | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextDayForecast"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_performance_api_v1_forecast_performance_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_snapshot_api_v1_live_snapshot_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_status_api_v1_live_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_stream_api_v1_live_stream_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ops_metrics_api_v1_ops_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_backtest_api_v1_optimization_backtest_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_scenario_api_v1_optimization_scenario_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quality_api_v1_quality_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityStage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    zones_api_v1_zones_get: {
        parameters: {
            query?: {
                borough?: string | null;
                /** @description name contains */
                q?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    zone_api_v1_zones__zone_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                zone_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ready"];
                };
            };
        };
    };
}
